### ISSUE TITLE
VU#475445 Multiple SAML libraries may allow authentication bypass via incorrect XML canonicalization and DOM traversal

### ISSUE THREAD

**Issue by elmuerte** [spring-projects/spring-security-saml#228]
**Notice**: with default settings spring-security-saml  _not_ vulnerable. Only if you configure the parser pool to not ignore comments you are at risk. See ticket content for more information.

---

See https://www.kb.cert.org/vuls/id/475445

I've been looking into this, and it does look like OpenSAML 2.6.4 does not properly process the content either. I have not proven it yet. But looking at the code the XML is processed as follows

In ``org.opensaml.xml.io.AbstractXMLObjectUnmarshaller.unmarshall(Element)``
```java
        Node childNode = domElement.getFirstChild();
        while (childNode != null) {

            if (childNode.getNodeType() == Node.ATTRIBUTE_NODE) {
                unmarshallAttribute(xmlObject, (Attr) childNode);
            } else if (childNode.getNodeType() == Node.ELEMENT_NODE) {
                unmarshallChildElement(xmlObject, (Element) childNode);
            } else if (childNode.getNodeType() == Node.TEXT_NODE
                    || childNode.getNodeType() == Node.CDATA_SECTION_NODE) {
                unmarshallTextContent(xmlObject, (Text) childNode);
            }
            
            childNode = childNode.getNextSibling();
        }
```

So ``user@user.com<!---->.evil.com`` is parsed as two TEXT nodes.

This eventually leads to ``org.opensaml.saml2.core.impl.AbstractNameIDTypeUnmarshaller.processElementContent(XMLObject, String)``
```java
    protected void processElementContent(XMLObject samlObject, String elementContent) {
        NameIDType nameID = (NameIDType) samlObject;
        nameID.setValue(elementContent);
    }
```

Which implies that the value of the NameID element will contain the last processed TEXT node. In the above example, ``.evil.com`` and not ``user@user.com.evil.com`` as one would expect.
This is unlike the presented example from the report where other libraries use the first TEXT node, i.e. ``user@user.com``.

**Comment by elmuerte** [comment]
FYI, the quickest way to stop this attack in your application (which uses spring-security-saml) is to make use of encrypted assertions on the IdP.

**Comment by csyperski** [comment]
So I'm trying to get up to speed on this, but it seems returning ".evil.com" is equally as bad as returning the first node (user@user.com) right?  In this case the bad guy just puts the target payload after the comment correct?  This may not be an easy when using an email address, but it is still very exploitable, correct?

**Comment by csyperski** [comment]
For example, let's say that the field in the response is a number and not an email address (as this applies not only to nameID).  Let's assume it is a user id, so as a bad guy, I could authenticate and the IDP could return 1971 as my ID and I could then insert a comment like so "1971" would then parsed user id would be "1" while maintaining the correct signature?  That seems bad.

**Comment by jebeaudet** [comment]
I've tried reproducing the issue by modifying a IdP initiated SAMLResponse using the POST binding and injecting a comment in the middle of all the assertions and I could not reproduce yet, the comment is correctly stripped from the assertion value and the whole text is returned. 

I've confirmed that the raw XML received on the endpoint has the comment however, I don't know yet who strips it, I'll dig a little more.

**Comment by jebeaudet** [comment]
Alright so I've found out why you *might* not be affected. The key here is a configuration property of the 2 `org.opensaml.xml.parse.ParserPool` implementations (`org.opensaml.xml.parse.BasicParserPool` and `org.opensaml.xml.parse.StaticBasicParserPool`). They both have a flag `ignoreComments` that is true by default. If you do *not* modify this flag, you should be safe from the vulnerability.

I have tested the issue with the flag `ignoreComments` set to `false` and I can confirm that the `SAMLResponse` gets consumed without error and that the assertion or NameID is modified as mentioned in the vuln report but it's using the text _after_ the comment tag like @elmuerte said. So something like : 
```
<saml2:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent">foo<!-- and a comment -->bar</saml2:NameID>
```
will resolve to `bar` in `org.springframework.security.saml.SAMLCredential::getNameId::getValue`.

I can confirm that the default bean definition in the sample is safe since it's using the default constructor.

**Comment by csyperski** [comment]
@jebeaudet Thanks for testing and reporting back!

**Comment by elmuerte** [comment]
@csyperski yes, using the last part is equally bad. Maybe not for email addresses, but if you use plain user ids then the user ``iamgroot`` can become ``iamg<!---->root``.

**Comment by elmuerte** [comment]
We're not completely in the clear. The ``ignoreComments`` setting is simply passed to the ``DocumentBuilderFactory``. So it depends on the used DOM implementation if comments can be ignored. The JRE default/Apache Xerces supports ``ignoreComments``. But Saxon does not support this feature.

OpenSAML uses the default JAXP ``DocumentBuilderFactory`` and provides no means to change this.

Thus if Saxon is your default JAXP DOM implementation then you are vulnerable. This is easy to figure out if this is the case. Saxon will throw a ``ParserConfigurationException`` when ``ignoreComments`` is enabled, so if Saxon is your default implementation then you would have made the above mentioned parser pool configuration change.

If you cannot change the default JAXP DOM implementation, then you will have to create your own subclass of the used ``ParserPool`` implementation and override ``initializePool`` to get a Xerces ``DocumentBuilderFactory`` (``org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl``).

**Comment by elmuerte** [comment]
I'm closing this ticket as the default set up is secure.

**Comment by rwinch** [comment]
Thank you for the report and help in the analysis. This analysis is correct. We are working on getting a more complete response to the exploit.

**Comment by gstanchev** [comment]
While this project is safe because of the defaults, it puts more urgency to upgrading to a version of OpenSAML that is actively supported as discussed on [#203](https://github.com/spring-projects/spring-security-saml/issues/203). According to the analysis above, the issue lies in the OpenSAML library itself, so the setIgnoringComments on the DocumentBuilderFactory just hides the issue. Both SAML 1.1 and SAML 2.0 allow http://www.w3.org/2001/10/xml-exc-c14n# **and** http://www.w3.org/2001/10/xml-exc-c14n#WithComments for Canonicalization method and reference transformation algorithm, so the defaults will break any IdP that issues tokens with comments in them (allowed by the standard). If we were on a branch that was maintained, then obviously upgrades to a fixed library would not need a breaking workaround.

**Comment by rwinch** [comment]
@gstanchev 

>  According to the analysis above, the issue lies in the OpenSAML library itself, so the setIgnoringComments on the DocumentBuilderFactory just hides the issue. 

Agreed. This is working around an issue. If the option breaks security, it really should not exist or at minimum be allowed to start with it set.

>  so the defaults will break any IdP that issues tokens with comments in them (allowed by the standard). 

I do not agree with this statement. Ignoring the comments is a choice of the SP parser and complies with the specification. Ignoring comments does not break the SP when the IdP issues comments in assertions.

> If we were on a branch that was maintained, then obviously upgrades to a fixed library would not need a breaking workaround.

I very much agree with this statement. Please see the newly updated [Spring Security SAML Roadmap](https://spring.io/blog/2018/03/05/spring-security-saml-roadmap). We'd love for you (and anyone else) to join us in helping update Spring Security SAML!

**Comment by gstanchev** [comment]
@rwinch Perhaps I am missing something, but if you set your parser to ignore comments, it will omit the comments on the DOM tree of the assertion it builds. If the assertion is signed with http://www.w3.org/2001/10/xml-exc-c14n#WithComments transformation and it has comments in it, the signature validation will fail because the DOM tree will not have those comments.

**Comment by elmuerte** [comment]
Ignoring comments will omit comment nodes, and thus they will not be included in the payload over which the digest is calculated. Thus the digest calculated by the SP will not match the digest provided by the IdP in the signature. 
A secure implementation with spring-security-saml does not support http://www.w3.org/2001/10/xml-exc-c14n#WithComments as canonicalization method for the signature. Note that the specification says that #WithComments is RECOMMENDED and not REQUIRED.

But also note that entity references are not fully supported. The specification does make full expansion of entity references required. But enabling processing of entity references is exploitable (see: XXE)
