### ISSUE TITLE
SamlTransformer & Base64

### ISSUE THREAD

**Issue by rwinch** [spring-projects/spring-security-saml#248]
Consider externalizing the Base64 encoding decoding to a different layer. This seems appropriate as Base 64 is more of a transport layer encoding.

**Comment by fhanik** [comment]
Thanks for the feedback. I have made the class package private. The encoding is set in stone and will not change due to the specs not being continued. While I like the idea of a _transport_ layer, I feel it is a bit over engineered for this use case. It is what makes OpenSAML so difficult to use.
SAML encoding/decoding should be super simple.
