### ISSUE TITLE
Remove "zombie" library dependency ca.juluisdavis:not-yet-commons-ssl

### ISSUE THREAD

**Issue by codefiddler** [spring-projects/spring-security-saml#263]
The update from spring-security-saml from 1.0.3 to 1.0.4 no longer uses the not-yet-commons-ssl version 0.3.9 but 0.3.17. For me a breaking change. But where do these library builds come from? Seems like a security issue to me. It just does not feel right.

Why is the project depending on ca.juluisdavis:not-yet-commons-ssl? This feels wrong because of the name but if you dig a little deeper, I cannot find the sources for this project.... on a security project?

references to http://juliusdavies.ca/commons-ssl/ do not exist. 

So please **remove** this dependency. For the following reasons

- using an updated un-findable dependency is not ok. Where is the source. The only version I found
  was https://github.com/krm1312/not-yet-commons-ssl (it only states it is a clone). References to original do not exist.
- the possibility of naming clashes and therefore class loading issues increases as this lib uses
  org.apache.commons as a base package.

**Comment by gstanchev** [comment]
I had a quick look around and found that the not-yet-commons-ssl's hostname verifier implementation is used throughout the project for whenever a hostname verification is needed (artifact resolution, probably metadata resolution, etc). There is a vulnerability logged against 0.3.9: CVE-2014-3604 which seems to affect the exact functionality that spring-security-saml is relying on - hostname verification. So staying on the same version is not an option. And the situation with the new version's distribution as outlined above is not good either - no source, private repo. I agree with the OP that some sort of action is needed - perhaps implement own hostname verifier or find another library that provides javax.net.ssl.HostnameVerifier implementation.

**Comment by gstanchev** [comment]
This is also confirmed by the documentation: [Dependencies](https://docs.spring.io/spring-security-saml/docs/current/reference/htmlsingle/#section-dependencies)

> Internal processing of SAML messages, marshalling and unmarshalling is handled by OpenSAML.
> 
> Spring SAML has a transitive dependency to library not-yet-commons-ssl. Inside Spring SAML this library is only used for hostname verifications and will be removed in case OpenSAML removes the dependency.

**Comment by krm1312** [comment]
Indeed, that CVE is exactly why I cloned that repo awhile ago (which is now gone??) and built internal dependencies of 0.3.17.  Just one of the rats nest of ancient security (real or not) issues that show due to the the ancient opensaml dependencies.  I really think for spring-security-saml to survive much longer a different or upgraded SAML library needs to be swapped in.  Even if it requires spring 5 / boot 2 at least there is an upgrade path.  Right now I fear this project is likely to become a dead end soon.

My current pom dependencies is a 100 lines of exclusions and specific versions (and non-central mirrors) to try to deal with it.

**Comment by mathisdt** [comment]
While migrating one of our applications to Java 10, I got a `NullPointerException` when initializing org.apache.commons.ssl.TrustMaterial. 

The reason was that Java 10 uses PKCS12 as default keystore format, but the trust store still is in JKS format. The library tries to load the trust store as PKCS12 file and fails - the only workaround I found is to tweak a security property _before the class is loaded_:

`Security.setProperty("keystore.type", "jks");`

Just for reference, if someone also stumbles over this. It would be much better if spring-security-saml didn't need this dependency!

**Comment by narupley** [comment]
FYI for anyone else who comes across this issue in Not-Yet-Commons-SSL...

I've forked the project and released a new version with fixes for Java 9+. It now handles PKCS12 files correctly, so TrustMaterial no longer throws a NPE.

You can find the project here: [Not-Going-To-Be-Commons-SSL](https://github.com/narupley/not-going-to-be-commons-ssl)

**Comment by jkubrynski** [comment]
Any progress with this issue?

**Comment by feradev** [comment]
Hi, I am seeking for advice on this issue.  We have developed an application using Spring/SAML and this dependency and the vulnerability are considered a big deal to our team.  Correct if I am wrong but would be correct if I say this issue is like we had a security hole in the security layer itself ?  This is causing us to think about alternatives, for example,  Could we use other Security extension with Spring ? 
We are thinking about even replacing Spring by other framework as we cannot afford security holes in our application.  Is there a chance this will be fixed/dependency removed in new Spring Releases ? Btw, We are wiling to upgrade to new Spring versions if fixes the issue.
Please advise, Thank you!

**Comment by fhanik** [comment]
@feradev @jkubrynski @narupley 

I have pushed the update of the library via https://github.com/spring-projects/spring-security-saml/commit/7ea40ddf03efe36c8c9e4295c3aae0ebe3277777

There will be a 1.0.8.RELEASE with this update. Maven Central is not syncing properly. But the Git tag is there.

**Comment by fhanik** [comment]
Commit didn't take place properly and Maven Central sync did not work. There will be a 1.0.8

**Comment by fhanik** [comment]
Fix completed. Please report any issues. 

Waiting on 1.0.8 to propagate through to Maven Central

https://search.maven.org/search?q=a:spring-security-saml2-core

**Comment by qiushile** [comment]
Could NOT work in FIPS mode in version 1.0.1.RELEASE due to ca.juluisdavis:not-yet-commons-ssl:0.3.9

**Comment by feradev** [comment]
Hello the fix really got rid off the dependency of not-yet-commons, thank you! but there is still a dependency on a vulnerable library though, httpclient-3.1, Would you know if there is a chance Spring will replace it in any future releases as well ?  We also have a dependency on a Apache library (openws 1.5.4) that we may try to replace by other one, it follows a screen capture of them:


![image](https://user-images.githubusercontent.com/11374632/57144695-fafec280-6d97-11e9-9adb-1076d5e1b27b.png)
