### ISSUE TITLE
Consider breaking up HostedProviderService

### ISSUE THREAD

**Issue by jgrandja** [spring-projects/spring-security-saml#308]
The `HostedProviderService` interface defines quite a few operations.

I'm wondering if it makes sense to split it up into multiple interfaces?

For example:

interface `MetadataProvider`
- `LocalMetadata getMetadata()`
- `RemoteMetadata getRemoteProvider(Saml2Object saml2Object)`
- `RemoteMetadata getRemoteProvider(String entityId)`
- `RemoteMetadata getRemoteProvider(ExternalProviderConfiguration c)`

interface `LogoutHandler`
- `LogoutRequest logoutRequest(RemoteMetadata recipient...`
- `LogoutResponse logoutResponse(LogoutRequest request...`

interface `Saml2Validator`
- `ValidationResult validate(Saml2Object saml2Object)`

interface `Saml2XmlSerializer` and `Saml2XmlDeserializer`
- `T fromXml(String xml, boolean encoded...`
- `String toXml(Saml2Object saml2Object)`
- `String toEncodedXml(Saml2Object saml2Object...`
- `String toEncodedXml(String xml, boolean deflate)`

The proposed interface names are just suggestions but I think the splitting up of responsibilities can simplify things and promote reuse via delegation-based strategy instead of inheritance.

**Comment by fhanik** [comment]
(SamlValidator)[https://github.com/spring-projects/spring-security-saml/blob/develop/core/src/main/java/org/springframework/security/saml/SamlValidator.java#L29] is an interface and component. 

The SAML (de)serializer is called (SamlTransformer)[https://github.com/spring-projects/spring-security-saml/blob/develop/core/src/main/java/org/springframework/security/saml/SamlTransformer.java#L26]

The LogoutHandler would be confusing, because the interface you suggest only creates skeleton objects. The actual (IDP LogoutHandler)[https://github.com/spring-projects/spring-security-saml/blob/develop/core/src/main/java/org/springframework/security/saml/provider/identity/IdentityProviderLogoutHandler.java#L55] and (SP LogoutHandler)[https://github.com/spring-projects/spring-security-saml/blob/develop/core/src/main/java/org/springframework/security/saml/provider/service/authentication/ServiceProviderLogoutHandler.java#L51] are handling log out logic.

The HostedProviderService is meant to be a simple API so that one doesn't have to delegate to multiple components for simple calls.

That's not meant that your suggestion is not valid. Maybe the hosted provider is too complete.

**Comment by fhanik** [comment]
Superseded by https://github.com/spring-projects/spring-security-saml/tree/feature/spring_sec_5.2_saml_mvp
