### ISSUE TITLE
Adding attributes to assertion generated by IdP

### ISSUE THREAD

**Issue by d8s** [spring-projects/spring-security-saml#322]
I see the assertion is generated in `HostedIdentityProviderService.assertion()`, and don't see that is looking for any custom attributes to add to the assertion. Is there a way to add attributes to assertion generated by the IdP?

**Comment by fhanik** [comment]
In the milestone version you would extend the `SamlProviderProvisioning` object that generates the provider service object.

I'm refactoring on a branch to simplify this to make it easier to extend.

**Comment by d8s** [comment]
Awesome. Thanks!

**Comment by marioleon** [comment]
Is there any updates about this one?

Right now, I'm dealing with exactly that scenario, I need to add a custom assertion attribute to the attribute statement object of an Assertion in order to send some data to the SP.

I'm trying an approach of creating a filter that I'll hook up right before the "IdpInitiatedLoginFilter" exxcutes (as that filter POST/Redirect to the SP when performing the actual filter logic) and see if I can add the attribute to the assertion from there before actually the filter post the SAMLResponse to the SP.

I truly feel this could be improved as it is not obvious and easy to figure out how to add the attributes.

Any suggestions if I should do it in a different way?

**Comment by fhanik** [comment]
@marioleon Thanks for the ping. I'll have time to work on this, this week.

**Comment by fhanik** [comment]
You can overwrite one or both of [these beans](https://github.com/spring-projects/spring-security-saml/blob/3d82e9d40787b515add63140c826cf8801cce10a/core/src/main/java/org/springframework/security/saml/provider/identity/config/SamlIdentityProviderServerBeanConfiguration.java#L46-L54)

```
	@Bean(name = "samlAssertionEnhancer")
	public AssertionEnhancer samlAssertionEnhancer() {
		return assertion -> assertion;
	}

	@Bean(name = "samlResponseEnhancer")
	public ResponseEnhancer samlResponseEnhancer() {
		return response -> response;
	}
```

**Comment by rohitkrishna094** [comment]
@fhanik Where to overwrite those beans? Also I have some roles(like ROLE_ADMIN, ROLE_USER in spring's authentication object). How do I add these roles as attributes in assertion? Thanks

**Comment by manjeesh** [comment]
@rohitkrishna094  did you find how to do this?

**Comment by Giddu** [comment]
An example project on adding additional custom attributes can be found in the repository  - https://github.com/gtiwari333/spring-security-saml-test-identity-provider-and-service-provider
