### ISSUE TITLE
Authentication statement is too old and maxAuthenticationAge

### ISSUE THREAD

**Issue by vrepetenko** [spring-projects/spring-security-saml#448]
Hi,

can not find out how to change maxAuthenticationAge in version 2.0.0.M30.
Any hint?

**Comment by MikeN123** [comment]
It's in `DefaultValidator`, you can override `samlValidator()` in `SamlServiceProviderServerBeanConfiguration` to configure it.

**Comment by ekaterinasmarp** [comment]
Hi, 

The way how we overriden it is the same as @MikeN123 suggested. 
The problem that I found there was the integer type of maxAuthenticationAge. We wanted to set it to one year and it is inpossible to fit one year milliseconds inside int datatype so that I needed to override `isDateTimeSkewValid` method as well. 

We were thinking about creation the pull request addressing this problem but not sure about backward compatibility. Any suggestions from the authors?

**Comment by vrepetenko** [comment]
Hi,

thanks for reply!

I just added in Application SecurityConfigurationn class:

```
    public SecurityConfiguration(@Autowired  SamlValidator samlValidator) {
        this.samlValidator = samlValidator;
        ((DefaultValidator)this.samlValidator).setMaxAuthenticationAgeMillis(2073600000); // 24 days
    }
```

I agree that Integer is too shot for this property.....

**Comment by jzheaux** [comment]
I believe this is resolved by https://github.com/spring-projects/spring-security-saml/pull/470
