### ISSUE TITLE
Multitenancy out of box support from 2.x

### ISSUE THREAD

**Issue by dhinesherode91** [spring-projects/spring-security-saml#476]
Currently we are working on a multitenant SaaS application where we are planning to support SSO using saml. We are planning to use spring security saml2 extension 1.0.10 release for achieving that. 
Our application contains multiple tenants where each tenant will have an unique Identity provider.
So we have to load the SSO request on run time based on current request where the tenant details will be available in the request context path. We are planning to extend SAMLContextProviderImpl for achieving the same.

But when I just surfed for any built in support, I could see the following post,
https://github.com/spring-projects/spring-security-saml/issues/312
where it is told that multitenant out of box support will be available from Spring security saml 2.x releases
I could see milestone releases for 2.x in maven. 
Can anyone please help me in getting any docs available regarding multitenant support from 2.x or help me with inputs?

Thanks in advance.

**Comment by rwinch** [comment]
Please take a look at the new SAML support in https://github.com/spring-projects/spring-security 

You can find documentation about multiple providers at https://docs.spring.io/spring-security/site/docs/current/reference/html/saml2.html#multiple-identity-provider-sample

If you have questions in the future, I'd consider posting to StackOverflow and tagging with #spring-security since this is the preferred place to ask questions.
