### ISSUE TITLE
Update esapi to 2.2.1.1

### ISSUE THREAD

**Issue by Veranicus** [spring-projects/spring-security-saml#491]
Dependency org.owasp.esapi:esapi:2.2.0.0 has a security vulnerability in commons-beanutils:commons-beanutils:1.9.3, specifically CWE-502.

**Comment by jzheaux** [comment]
Thanks for the report, @Veranicus. Have you already reached out to [ESAPI ](https://github.com/ESAPI/esapi-java-legacy) about it? Since they are directly dependent on it, that's the ideal place to fix this.

**Comment by frombrest** [comment]
Dependency: commons-collections:commons-collections:jar:3.2.1:compile
https://nvd.nist.gov/vuln/detail/CVE-2015-6420

**Comment by jzheaux** [comment]
@frombrest, the most recent GA version already uses `3.2.2`, or did I misunderstand?

**Comment by jzheaux** [comment]
[The ESAPI 2.2.1.1 release is not backward compatible](https://github.com/ESAPI/esapi-java-legacy/commit/b5638c25ba54d808b5d40de239fc80659493e985#diff-71307c3129ed1470d6955a5358c32145) with the latest 2.x OpenSAML version. Since there are no planned releases for OpenSAML 2.x, it's unlikely that Spring Security SAML will be able to take the upgrade.

For those needing `commons-beanutils:1.9.4`, consider specifying the dependency in your POM.

For those needing `esapi:2.2.1.1`, you will need to extend `org.opensaml.DefaultBootstrap` to override the `initializeESAPI` method and create your own implementation of `org.owasp.esapi.SecurityConfiguration`.
