### ISSUE TITLE
Can I integrate the second authentication method on the basis of integrating SAML?

### ISSUE THREAD

**Issue by EightMonth** [spring-projects/spring-security-saml#503]
My application integrates SAML, but now users who want to introduce a third party can log in to the application. When my application can successfully obtain third-party user information, it is found that the request will be intercepted by SAML again, which is regarded as an invalid request.
What can I do to meet my needs?

Best Regards
Eightmonth

**Comment by jzheaux** [comment]
Hi, @EightMonth, thanks for reaching out.

I think that [StackOverflow](https://stackoverflow.com) would likely be a better place to address your question. Would you mind posting it there and including an example flow of requests that leads to the error? I'd also be interested to know more about your application's configuration. 

I'm going to close this as addressed. Once you post the question to StackOverflow, please link that back here so that others can find the rest of the conversation, and I'm happy to follow up on the StackOverflow question, too.
