### ISSUE TITLE
how to handle URL encoding in SAML response

### ISSUE THREAD

**Issue by minaksheej** [spring-projects/spring-security-saml#514]
Hi ,
I  am using spring-security-saml for SSO..its worked fine on my local system..while I have deployed it ,stopped working 
I found the saml response that I am receiving on server is having having URL encoding over base64 encoded response
and while saml is decoding the response its giving error..Please help me how I can solve this

**Comment by jzheaux** [comment]
Thanks for getting in touch, we'd love to help! Will you please post this question to [Stack Overflow](https://stackoverflow.com/)? Then, share the link here so that others can find it. We use GitHub only for [bug reports and feature requests](https://github.com/spring-projects/spring-framework/blob/master/CONTRIBUTING.md#discuss).

Or, if you feel this is a genuine Spring Security bug, please provide a minimal sample that reproduces the issue.
