### ISSUE TITLE
spring-security-saml2 opensaml v.2 dependency conflict with opensaml v.3

### ISSUE THREAD

**Issue by surkoff-v** [spring-projects/spring-security-saml#515]
We are using **1.0.10.RELEASE** and now have conflict opensaml **v.2** and opensaml **v.3** (which is a dependency for spring-ws-security)
`org.opensaml.core.xml.schema.impl.XSAnyBuilder cannot be cast to class org.opensaml.xml.XMLObjectBuilder`
Is it the only solution to migrate to **2.0.0.M31** (as i understand it could be time consuming) Or may be exists old version branch with upgraded dependency to opensaml **v.3**.
May be there is other solution?

**Comment by jzheaux** [comment]
Since this project is in maintenance mode, please consider using [`spring-security-saml2-service-provider`](https://github.com/spring-projects/spring-security/tree/main/saml2/saml2-service-provider) instead, which is actively supported and [documented](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#servlet-saml2).

Note that `spring-security-saml2-service-provider` supports both OpenSAML 3 and 4, though 4 is recommended since 3 has reached end-of-life.
