### ISSUE TITLE
EmptyStorageFactory Questions for Replay Prevention

### ISSUE THREAD

**Issue by jwangmitra** [spring-projects/spring-security-saml#524]
My team is looking to implement the property below as a solution for InReponseTo validation for HTTP session. If we were to use the EmptyStorageFactory setting in securityContext.xml, are there other checks that we would be losing checks on SP side or would we also be losing some validation checks on the unsolicited response from IDP?

<bean id="contextProvider"
class="org.springframework.security.saml.context.SAMLContextProviderImpl">

<property name="storageFactory">
<bean
class="org.springframework.security.saml.storage.EmptyStorageFactory" />
</property>
</bean>

Sorry if this is not the right place, was unable to find information on this topic elsewhere.

**Comment by jzheaux** [comment]
Hi, @jwangmitra, thanks for reaching out. Since this project is now EOL, I'd recommend you try and use [Spring Security's built-in SAML support](https://docs.spring.io/spring-security/reference/5.6.2/servlet/saml2/index.html) instead of this extension.

As to your question about where is the right place to ask these questions, I'd recommend [StackOverflow](https://stackoverflow.com). Please feel free to post a link to your posted question here so that I and others can find it and respond.
